version: "3"
services:
  nginx:
    ports:
      - "3000:80"
  node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=michu
      - MONGO_PASSWORD=password
      - SESSION_SECRET=gvjgfccfSFFcf4747FFFdjdbfFFDocbw3
    command: npm run dev
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=michu
      - MONGO_INITDB_ROOT_PASSWORD=password
